#!/bin/sh
mvn clean package && docker build -t parmardhawaldocker/ConsumerDB .
docker rm -f ConsumerDB 2>/dev/null || true && docker run -it --name ConsumerDB -p 8080:8080 -p 4848:4848 -p 8181:8181 --name ConsumerDB parmardhawaldocker/ConsumerDB
