#!/bin/sh
mvn clean package && docker build -t krutiakbari1723/DocFrontApp .
docker rm -f DocFrontApp 2>/dev/null || true && docker run -it --name DocFrontApp -p 8080:8080 -p 4848:4848 -p 8181:8181 --name DocFrontApp krutiakbari1723/DocFrontApp
