#!/bin/sh
#deploy="false"
deploy="true"

image=DocFrontApp
version=1.0-SNAPSHOT
latest=true

#OPTIONS="--no-cache --force-rm"
#OPTIONS="--no-cache"
#OPTIONS="--force-rm"
OPTIONS=""

docker build ${OPTIONS} -t krutiakbari1723/${image}:1.0-SNAPSHOT .
if [ "$?" -eq 0 ] && [ ${deploy} == "true" ]; then
    docker push krutiakbari1723/${image}:1.0-SNAPSHOT
    if [ "$latest" == "true" ]; then
        docker tag krutiakbari1723/${image}:1.0-SNAPSHOT krutiakbari1723/${image}:latest
        docker push krutiakbari1723/${image}:latest
    fi
fi