#!/bin/sh
mvn clean package && docker build -t krutiakbari1723/DocAvailabilityApp .
docker rm -f DocAvailabilityApp 2>/dev/null || true && docker run -it --name DocAvailabilityApp -p 8080:8080 -p 4848:4848 -p 8181:8181 --name DocAvailabilityApp krutiakbari1723/DocAvailabilityApp
