#!/bin/sh
mvn clean package && docker build -t parmardhawaldocker/ProducerDB .
docker rm -f ProducerDB 2>/dev/null || true && docker run -it --name ProducerDB -p 8080:8080 -p 4848:4848 -p 8181:8181 --name ProducerDB parmardhawaldocker/ProducerDB
